portfolio_management/urls.py
from django.contrib import admin
from django.urls import path
from manager import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.home , name="home"),
    path('sync/', views.sync, name="sync airtable"),
    path("login/" , views.log_in , name="log_in"),
    path('log_out/', views.log_out, name = 'log_out'),
    path('entities/<str:name>/', views.entity_view, name='entity_view'),
    path('companies/<str:name>/', views.company_view, name='company_view'),
    path('dashboard/', views.dashboard, name = 'dashboard'),
    path('adminDashboard/', views.adminDashboard, name = 'adminDashboard'),
    path('portfolio/', views.portfolio, name = 'portfolio'),
    path('adminPortfolio/', views.adminPortfolio, name = 'adminPortfolio'),
    path('entities/', views.entities, name = 'entities'),
    path('adminEntities/', views.adminEntities, name = 'adminEntities'),
    path('founders/', views.founders, name = 'founders'),
    path('adminFounders/', views.adminFounders, name = 'adminFounders'),
    path('ecosystem/', views.ecosystem, name = 'ecosystem'),
    path('adminEcosystem/', views.adminEcosystem, name = 'adminEcosystem'),
    path('users/', views.users, name = 'users'),
    path('adminAddUser/', views.adminAddUser, name='adminAddUser'),
    path('adminDeleteUser/<int:userID>', views.adminDeleteUser, name='adminDeleteUser'),
    path('adminDeleteCompany/<int:compID>', views.adminDeleteCompany, name='adminDeleteCompany'),
    path('adminEditUser/<int:userID>', views.adminEditUser, name='adminEditUser'),
    path('add/companySpreadsheet', views.addCompany, name = 'add_company'),
    path('add/company', views.addCompanyOne, name = 'add_company_one'),
    path('add/founder',views.addFounderOne, name = 'add_founder_one'),
    path('add/investor',views.addInvestorOne, name = 'add_investor_one'),
    path('add/right',views.addRightOne, name = 'add_right_one'),
    path('add/round',views.addRoundOne, name = 'add_round_one'),
    path('adminProhibitted/', views.adminProhibitted, name='adminProhibitted'),
    path('companies/<str:company_name>/founders/', views.company_founders, name='company_founders'),
    path('companies/<str:company_name>/investors/', views.company_investors, name='company_investors'),


    path('companies/<str:company_name>/rounds/', views.company_rounds, name='company_rounds'),
    path('companies/<str:company_name>/rights/', views.company_rights, name='company_rights'),

    path('deleteCompanyFounder/<int:compID>/<int:founderID>', views.deleteCompanyFounder, name='deleteCompanyFounder'),
    path('deleteCompanyInvestor/<int:compID>/<int:investorID>', views.deleteCompanyInvestor, name='deleteCompanyInvestor'),
    path('deleteCompanyRound/<int:compID>/<int:roundID>', views.deleteCompanyRound, name='deleteCompanyRound'),
    path('deleteCompanyRight/<int:compID>/<int:rightID>', views.deleteCompanyRight, name='deleteCompanyRight'),

    path('reset_password' , auth_views.PasswordResetView.as_view(template_name="password_reset.html"), name='reset_password'),
    path('reset_password_sent', auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"), name='password_reset_confirm'),
    path('reset_password_complete/' , auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_complete.html") , name= "password_reset_complete")
]


handler404 = views.error_404

manager/models.py
from django.core.validators import MinValueValidator
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager
from pandas._libs.tslibs.parsing import parse_datetime_string

# Create your models here.

class User(AbstractUser):
    USER_TYPE_CHOICES = (
        (1, 'viewer'),
        (2, 'admin'),
    )
    first_name = models.CharField(max_length=30, help_text='Enter firstname')
    last_name = models.CharField(max_length=30, help_text='Enter lastname')
    username = models.EmailField(max_length = 50, unique = True, help_text = 'Enter a unique email')
    
    user_type = models.PositiveSmallIntegerField(choices = USER_TYPE_CHOICES)

    REQUIRED_FIELDS=["user_type"]
    def full_name(self):
        return (self.first_name + " " + self.last_name) #Get string with name and surname
    

    objects: UserManager = UserManager()

class Entity(models.Model):
    name = models.CharField(max_length=50)

    ## The following is made only to appease the type checker (No special stuff here)
    invested_company: models.QuerySet["Company"]
    founding_company: models.QuerySet["Company"]
    def __str__(self):
        return self.name

    def getName(self):
        return self.name

    def getTotalFoundedCompanies(self):
        return self.founding_company.count()

    def getTotalInvestedCompanies(self):
        return self.invested_company.count()

class Company(models.Model):
    name = models.CharField(max_length=50)
    number = models.CharField(max_length=50, blank=False, null=False)
    country_code = models.CharField(max_length=15)
    wayra_investment = models.DecimalField(max_digits=10, decimal_places=3, default=0.0)
    description = models.CharField(max_length=200, blank=True, null=True)
    investors = models.ManyToManyField(
            Entity,
            through='Investing',
            through_fields=('company','investor'),
            related_name='invested_company'
        )
    founders = models.ManyToManyField(
            Entity,
            related_name='founding_company'
            )
    wayra_right: models.QuerySet["Right"]
    rounds = models.QuerySet["Round"]

    def update_comp(self, new_info: dict):
        self.name = new_info['Company']
        self.country_code = new_info['Hub']
        self.description = new_info['Description (ENG)']
        self.wayra_investment = new_info['Wayra Total Investment (ML)']
        self.save()

    def isPortfolio(self):
        return self.wayra_investment != 0

    def __str__(self):
        return self.name

    def getTotalInvestors(self):
        return self.investors.count()

    def getTotalFounders(self):
        return self.founders.count()

    def getTotalRounds(self):
        return self.rounds.count()

    def getTotalRights(self):
        return self.wayra_right.count()


class Investing(models.Model):
    investor = models.ForeignKey(Entity, on_delete=models.CASCADE, null=False)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, null=False)

    amount = models.DecimalField(max_digits = 20, decimal_places=3, null=False,validators = [MinValueValidator(0)])

    def get_amount(self):
        return self.amount

class Round(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name="rounds")
    round_number = models.PositiveSmallIntegerField(validators=[MinValueValidator(0)])
    equity = models.DecimalField(max_digits=20, decimal_places=3, validators = [MinValueValidator(0)], default=0)
    wayra_equity=models.DecimalField(max_digits=20, decimal_places=3, validators = [MinValueValidator(0)], default=0)

    pre_money_valuation = models.DecimalField(max_digits=20, decimal_places=3, validators = [MinValueValidator(0)], default=0)

    round_date = models.DateField(null=True)
    def update_round(self, new_info: dict):
        self.equity = new_info.get(f"(Round {self.round_number}) - Investors Equity") or 0
        self.wayra_equity = new_info.get(f"(Round {self.round_number}) - Wayra Follow-on") or 0
        date_str:str = new_info.get(f"(Round {self.round_number}) - Date Link") or ""
        self.round_date = parse_datetime_string(date_str, dayfirst=True, yearfirst=False)
        self.pre_money_valuation = new_info.get(f"(Round {self.round_number}) - Pre-money valuation") or 0
        self.save()

    def __str__(self) -> str:
        return f"{self.company.name} Round:{self.round_number}"

class Right(models.Model):
    name = models.CharField(max_length=50)
    holding_right = models.ManyToManyField(Company, related_name="wayra_right")

class Document(models.Model):
    upload = models.FileField(upload_to='documents/')

manager/forms.py
from django import forms
from .models import *
from django.core.validators import RegexValidator, MinValueValidator, FileExtensionValidator
from django.forms import ModelForm
from decimal import Decimal


class LoginForm(forms.Form):

    username_attrs = {
        'id':'username',
        'name': 'username',
        'class': 'form-control',
        'id':'username',
        'placeholder':"Username"
    }

    password_attrs = {
        'id':'password',
        'name':'password',
        'class':'form-control',
        'id':'password',
        'placeholder':"************"
    }

    username = forms.CharField(label='', widget=forms.TextInput(attrs=username_attrs))
    password = forms.CharField(label='', widget=forms.PasswordInput(attrs=password_attrs))

class DocumentForm(ModelForm):
    class Meta:
        model = Document
        fields = ['upload']
        validators = [
            FileExtensionValidator(allowed_extensions=['xlsx'])
        ]

class CompanyForm(forms.Form):
    name = forms.CharField(max_length=50)
    number = forms.CharField(max_length=50)
    country_code = forms.CharField(max_length=15)
    wayra_investment = forms.DecimalField(max_digits=10, decimal_places=3, validators=[MinValueValidator(Decimal('0.00'))])
    description = forms.CharField(max_length=200)
    founder_Name = forms.CharField(max_length=50)
    
class InvestorForm(forms.Form):
    name = forms.CharField(max_length=50, required=True)
    company = forms.CharField(max_length=50, required=True)
    amount = forms.DecimalField(max_digits=10, decimal_places=3, validators=[MinValueValidator(Decimal('0.00'))])


class RightForm(ModelForm):
    class Meta:
        model = Right
        fields = ['name','holding_right']

class RoundForm(ModelForm):
    class Meta:
        model = Round
        fields = ['company','round_number','equity','wayra_equity','pre_money_valuation']

class FounderForm(forms.Form):
    name = forms.CharField(max_length=50, required=True)
    company = forms.CharField(max_length=50, required=True)

class AddNewUser(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']
        help_texts = { 'first_name': None, 'last_name': None, 'email': None}

    password = forms.CharField(
        label = 'Password',
        widget = forms.PasswordInput(),
        validators = [ # validates that the input matches the requirements
            RegexValidator(
                regex = r'^(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9]).*$',
                message = 'Password must contain an uppercase character, a lowercase character and a number'
            ),
        ]
    )
    password_confirmation = forms.CharField(label = 'Password Confirmation', widget = forms.PasswordInput())

    def clean(self): # checks if the password matches the confirm password
        super().clean()
        password = self.cleaned_data.get('password')
        password_confirmatiuon = self.cleaned_data.get('password_confirmation')
        if password != password_confirmatiuon:
            self.add_error('password_confirmation', 'Confirmation password does not match the password.') # creates an erro

    def save(self): # creates a new user
        super().save(commit=False)
        user = User.objects.create_user(
            self.cleaned_data.get('email'),
            first_name = self.cleaned_data.get('first_name'),
            last_name = self.cleaned_data.get('last_name'),
            email = self.cleaned_data.get('email'),
            password = self.cleaned_data.get('password'),
            user_type = 1
        )
        return

manager/templates/addCompany.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Company</title>
    <link rel="icon" type="image/x-icon" href="{% static 'Wayra-Icon-Black.ico' %}">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    
    <link rel="stylesheet" href="{% static 'css/addCompany.css' %}">

</head>

<div class="main">
  <h1>Add Companies</h1>
  <h2>Upload Companies Spreadsheet: </h2>
  
  {% if message %}
    <p>{{ message }}</p>
  {% endif %}

  {% if error %}
    <p style="color: red;">{{ error }}</p>
  {% endif %}

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input value="New Company File" type="submit">
  </form>
</div>

manager/templates/addFounderOne.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="{% static 'Wayra-Icon-Black.ico' %}">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    
    <link rel="stylesheet" href="{% static 'css/addCompany.css' %}">

</head>
{% block body %}
<div>
  <h2>Add Founder: </h2>
  
  {% if message %}
    <p>{{ message }}</p>
  {% endif %}

  {% if error %}
    <p style="color: red;">{{ error }}</p>
  {% endif %}

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input value="Submit Founder" type="submit">
  </form>
</div>
{% endblock %}

manager/templates/addInvestorOne.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="{% static 'Wayra-Icon-Black.ico' %}">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    
    <link rel="stylesheet" href="{% static 'css/addCompany.css' %}">

</head>
{% block body %}
<div>
  <h2>Add Investor: </h2>
  
  {% if message %}
    <p>{{ message }}</p>
  {% endif %}

  {% if error %}
    <p style="color: red;">{{ error }}</p>
  {% endif %}

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input value="Submit Investor" type="submit">
  </form>
</div>
{% endblock %}

manager/templates/adminDashboard.html
{% extends 'adminBase.html' %}
{% load static %}
{% load humanize %}

{% block title %}
<title> {{ request.user.full_name }}'s Dashboard</title>
{% endblock %}

{% block contents %}
<h1 class="mt-4">{{ request.user.full_name}}'s Dashboard</h1>

<div class="row gx-5">
  {# <h1>{{ request.user.full_name}}'s Dashboard</h1> #}
    <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6">
      <div class="card-counter">
        <i class="fa fa-building"></i>
        <span class="count-numbers">{{ totalInvestors }}</span>
        <span class="count-name">Investors</span>
      </div>
    </div>

    <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6">
      <div class="card-counter">
        <i class="fa fa-money"></i>
        <span class="count-numbers">£{{ totalInvestment }}{{ investUnit }}</span>
        <span class="count-name">Investment</span>
      </div>
    </div>

    <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6">
      <div class="card-counter">
        <i class="fa fa-briefcase"></i>
        <span class="count-numbers">{{ totalCompanies }}</span>
        <span class="count-name">Portfolio Companies</span>
      </div>
    </div>

    <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6">
      <div class="card-counter">
        <i class="fa fa-users"></i>
        <span class="count-numbers">{{ totalFounders }}</span>
        <span class="count-name">Founders</span>
      </div>
  </div>
</div>

<div class="row gx-5">
  <div class="col-lg-6">
    <div class="panel panel-default">
      <div class="panel-heading"><i class="fas fa-chart-bar me-1"></i><span> Top Company Investments </span></div>
      <div class="panel-body"><canvas id="myBarChart" width="100%" height="40"></canvas></div>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="panel panel-default">
      <div class="panel-heading"><i class="fas fa-chart-bar me-1"></i><span>Company Demographic</span></div>
      <div class="panel-body"><canvas id="MyDoughnutChart" width="100%" height="40"></canvas></div>
    </div>
  </div>
</div>

<div class="row gx-5">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading"><i class="fas fa-chart-bar me-1"></i><span>Top Firms' Pre-Money Valuations</span></div>
      <div class="panel-body"><canvas id="myLineGraph" width="100%" height="40"></canvas></div>
    </div>
  </div>
</div>

<script>
  new Chart(document.getElementById("MyDoughnutChart"), {
    type: 'doughnut',
    data: {
      labels: {{ doughnutLabels | safe }},
      datasets: [
        {
          label: "Countries",
          backgroundColor: ["#3e95cd", "#8e5ea2","#3cba9f","#e8c3b9","#c45850"],
          data: {{ doughnutData | safe }},
        }
      ]
    },
    options: {
      title: {
        display: true,
        text: 'Company Locations'
      }
    }
  });
</script>

<script>
new Chart(document.getElementById("myBarChart"), {
  type: 'bar',
  data: {
    labels: {{ barLabels | safe}},
    datasets: [{
      label: "Wayra Investment",
      backgroundColor: "rgba(2,117,216,1)",
      borderColor: "rgba(2,117,216,1)",
      data: {{ barData | safe }},
    }],
  },
  options: {
    scales: {
      xAxes: [{
        gridLines: {
          display: true
        },
      }],
      yAxes: [{
        gridLines: {
          display: true
        }
      }],
    },
    legend: {
      display: false
    }
  }
});
</script>

<script>
var xValues = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];

new Chart("myLineGraph", {
  type: "line",
  data: {
    labels: {{ lineLabels | safe }},
    datasets: [{
      data: {{ lineData1 | safe }},
      borderColor: "red",
      fill: false,
      label: {{ lineName1 | safe }}
    },{
      data: {{ lineData2 | safe }},
      borderColor: "green",
      fill: false,
      label: {{ lineName2 | safe }}
    },{
      data: {{ lineData3 | safe }},
      borderColor: "blue",
      fill: false,
      label: {{ lineName3 | safe }}
    },{
      data: {{ lineData4 | safe }},
      borderColor: "purple",
      fill: false,
      label: {{ lineName4 | safe }}
    },{
      data: {{ lineData5 | safe }},
      borderColor: "black",
      fill: false,
      label: {{ lineName5 | safe }}
    },]
  },
  options: {
    legend: {display: true}
  }
});

</script>


{% endblock %}

{% block scripts %}



{% endblock %}

manager/templates/adminEntities.html
{% extends 'adminBase.html' %}
{% load static %}

{% block title %}
<title>Investors</title>
{% endblock %}

{% block contents %}
<h1 class="mt-4">All Investors</h1>

<h1></h1>

<div class="btn-group">

  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Add new records <span class="caret"></span>
  </button>

  <ul class="dropdown-menu">
    <li><a href="{% url 'add_investor_one' %}">Manual Entry</a></li>
  </ul>

</div>

<h1></h1>

{% include 'partials/entity_table.html' with data=data %}
{% include 'partials/tables_javascript.html' %}
{% endblock %}

manager/templates/adminFounders.html
{% extends 'adminBase.html' %}
{% load static %}

{% block title %}
<title>Founders</title>
{% endblock %}

{% block contents %}
<h1 class="mt-4">All Founders</h1>

<h1></h1>

<div class="btn-group">

  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Add new records <span class="caret"></span>
  </button>

  <ul class="dropdown-menu">
    <li><a href="{% url 'add_founder_one' %}">Manual Entry</a></li>
  </ul>

</div>

<h1></h1>

{% include 'partials/founders_table.html' with data=data %}
{% include 'partials/tables_javascript.html' %}
{% endblock %}

manager/templates/admin_edit_user.html
{% extends 'adminBase.html' %}
{% load static %}

{% block title %}
<title>Edit Users</title>
{% endblock %}

{% block contents %}
<h1>Edit User</h1>
<p>Replace below details to edit this account</p>

{# {{ form.non_field_errors }} #}

{% for message in messages %}
  <div class="alert alert-danger" role="alert">
    {{ message }}
  </div>
{% endfor %}

<strong>User ID: {{ account.id }}</strong>
<br></br>
{# <p>&nbsp</p> #}
<form action = "{% url 'adminEditUser' account.id %}" method = "post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    {# {{ form.as_p }} #}
    <input type="submit" value="Submit" onclick="return confirm('Are you sure all details are correct?');">
</form>


{% endblock %}

manager/templates/entity_details.html
{% extends "base_content.html" %}
{% load static %}

{% block title %}
<title>{{ entity.name }} - Entity , Funding, Investing & Financials </title>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.3/css/dataTables.jqueryui.min.css">
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/entityDetails.css' %}">
<div class="container-fluid">
  <div class="row">
    <div class="header-nav">
      <h1 class="page-header search-header">{{ entity.name }}</h1>
    </div>
  </div>    
  <div class="row">
    <div class="card">
      {% comment %} <div class="card card-about">
        <h2 class="card-h2">About</h2>
          <p>Information about the company goes here</p>
      </div> {% endcomment %}
    </div>
      <div class="card-container">
        <div class="card card-about">
          <h2 class="card-h2">Investing Companies</h2>
            <div class="detailed-table">
              <table id="investing-companies">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Country Code</th>
                    <th>Name</th>
                    <th>Amount invested</th>
                  </tr>
                </thead>
                <tbody>
                  {% for company in entity.invested_company.all %}
                    <tr>
                      <td> {{ company.id }} </td>
                      <td>{{ company.country_code }}</td>
                      <td><a href="{% url 'company_view' company.name %}">{{ company.name }}</a></td>
                      <td>
                        {% for investment in entity.investing_set.all %}
                          {% if investment.company == company %}
                              {{ investment.amount }}
                          {% endif %}
                        {% endfor %}
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
        </div>
        <div class="card card-news">
          <h2 class="card-h2">Founding Companies</h2>
          <div class="detailed-table">
            <table id="founding-companies">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Country Code</th>
                  <th>Name</th>
                </tr>
              </thead>
              <tbody>
                {% for company in entity.founding_company.all %}
                  <tr>
                    <td> {{ company.id }} </td>
                    <td>{{ company.country_code }}</td>
                    <td><a href="{% url 'company_view' company.name %}">{{ company.name }}</a></td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
</div>
{% include 'partials/tables_javascript.html' %}

<script>
    let investingCompaniesTable = $('#investing-companies').DataTable({
      "scrollX": true,
      "autoWidth": false
    });
    let foundingCompaniesTable = $('#founding-companies').DataTable({
      "scrollX": true,
      "autoWidth": false
    });
</script>

{% endblock %}